name: Nix actions

on:
  pull_request:
  push:
    branches:
      - main
      - gha
  workflow_dispatch:

jobs:
  nix-matrix:
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#systems')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-check:
    name: "Nix flake check"
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GH_TOKEN_REPO_ACCESS }}
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GH_TOKEN_REPO_ACCESS }}
            trusted-public-keys = cache.plex.bz:Vdh+jRJPqfHyL3Mq5fHqRVMOoI3Jg6eSXkafBgY2eRU= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = s3://cache.plex.bz https://cache.nixos.org/
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PLEX_NIX_SSH_PRIVATE_KEY }}

      - run: nix flake check -L --show-trace
