name: Nix actions

on:
  pull_request:
  push:
    branches:
      - main
      - gha
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  nix-matrix:
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#systems')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  # nix-build:
  #   name: "Build and cache the packages"
  #   runs-on: buildjet-32vcpu-ubuntu-2204
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: cachix/install-nix-action@v27
  #       with:
  #         github_access_token: ${{ secrets.GH_TOKEN_REPO_ACCESS }}
  #         extra_nix_config: |
  #           access-tokens = github.com=${{ secrets.GH_TOKEN_REPO_ACCESS }}
  #           trusted-public-keys = cache.plex.bz:Vdh+jRJPqfHyL3Mq5fHqRVMOoI3Jg6eSXkafBgY2eRU= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  #           substituters = s3://cache.plex.bz https://cache.nixos.org/
  #           max-jobs = auto
  #           require-sigs = true
  #           sandbox = true

  #     - uses: webfactory/ssh-agent@v0.9.0
  #       with:
  #         ssh-private-key: ${{ secrets.PLEX_NIX_SSH_PRIVATE_KEY }}


  #     - run: nix build ".#cppStdenv" -L --show-trace

  nix-check:
    name: "Nix flake check"
    runs-on: buildjet-32vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::362267952554:role/nix-binary-cache-writer-user
          role-session-name: nixer-ci
          aws-region: us-east-1
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GH_TOKEN_REPO_ACCESS }}
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GH_TOKEN_REPO_ACCESS }}
            trusted-public-keys = cache.plex.bz:Vdh+jRJPqfHyL3Mq5fHqRVMOoI3Jg6eSXkafBgY2eRU= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = s3://cache.plex.bz https://cache.nixos.org/
            max-jobs = auto
            require-sigs = true
            sandbox = true

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PLEX_NIX_SSH_PRIVATE_KEY }}

      - run: nix flake show --show-trace
      - run: nix flake check -L --show-trace
      - run: nix build ".#devShells.x86_64-linux.cpp" --show-trace
      - run: echo "'${{ secrets.NIX_CACHE_SIGNING_KEY }}'" > cache.key
      - run: nix copy --all --to 's3://cache.plex.bz?compression=zstd&compression-level=15&secret-key=cache.key'
      - run: rm cache.key
